# Generated by Django 3.2.5 on 2021-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_fpost_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpost',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
